### ISSUE TITLE
How can I use 'combo'?

### ISSUE THREAD

**Issue by sbcreox** [jprante/elasticsearch-plugin-bundle#12]
Hello,

I was upgrade my ElasticSearch from 1.4.2 to 2.2.0. I was using gem: https://github.com/jprante/elasticsearch-analysis-german and it includes 'elasticsearch-analysis-combo'. In readme is writing that you use also combo(...combo: apply more than one analyzer on a field...), but when I use type: 'combo' in my code I got error: 
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"illegal_argument_exception","reason":"Unknown Analyzer type [combo] for [default]"},"status":400}
```

Here is setting:
```
...
analyzer: {
  german:      {
    filter:    %w(lowercase trim icu_folding icu_normalizer german_snow german_stop),
    type:      'custom',
    tokenizer: 'icu_tokenizer',
  },
  default: {
    sub_analyzers: %w(standard german),
    type:          'combo'
  }
}
...
```
I got installed plugin in ES and server was reloaded many times :)

Do you have some idea, what is wrong in my code?

Thank you

**Comment by jprante** [comment]
The `combo` analyzer is not compatible to Elasticsearch 2.x and was removed. I will fix the README.

**Comment by sbcreox** [comment]
Thanks for answer, I was change my code from ES guide and it seems that everything works. Have a nice day.
