### ISSUE TITLE
Installation link 404

### ISSUE THREAD

**Issue by bsimm** [jprante/elasticsearch-plugin-bundle#2]
I'm currently trying to install this plugin bundle and the installation link 404's

**Comment by jprante** [comment]
The URL is http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/1.4.0.6/elasticsearch-plugin-bundle-1.4.0.6-plugin.zip

**Comment by bsimm** [comment]
Thanks!
