### ISSUE TITLE
ES 5.1 alread useable?

### ISSUE THREAD

**Issue by ThaDafinser** [jprante/elasticsearch-plugin-bundle#23]
First off thank you for this bundle - looks really promising.

In the README the compability matrix says, it's already compatible with ES 5.1.

When i browser to some plugins, they seem to be a bit older, like https://github.com/jprante/elasticsearch-analysis-german

I also don't find the 5.1.1.0 release here https://github.com/jprante/elasticsearch-plugin-bundle/releases
or here https://repo1.maven.org/maven2/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/
like mentioned in the docs.

**Comment by ThaDafinser** [comment]
I just found here a newer download repo
http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/5.1.1.0/

**Comment by jprante** [comment]
I am cleaning up and reviewing my work. The other plugins will be "subplugins" of the bundle plugin but are not all in place yet.

The docs are out of sync.

Feel free to try out 5.1.1.0, which is a preview release. There will be 5.1.1.1+ versions with revised code.

**Comment by ThaDafinser** [comment]
Builds are available until `5.2` http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/

Thanks
