### ISSUE TITLE
Bug with elasticsearch 1.4.4? 

### ISSUE THREAD

**Issue by mablae** [jprante/elasticsearch-plugin-bundle#4]
When installing the plugin in v.1.4.6.0 to ES 1.4.4 I was not able to recreate my index: 

 [Elastica\Exception\Connection\HttpException]
  Operation timed out

I updated to Elasticsearch 1.5 and reinstalled recent bundle plugin version => Error is gone

**Comment by jprante** [comment]
Correct, there is no plugin version for ES 1.4.4

**Comment by mablae** [comment]
Okay, then please close :-)

**Comment by jprante** [comment]
I released a 1.4.4.0 version (which is identical to 1.5.1.0) for Elasticsearch 1.4.4 to avoid misunderstandings.

**Comment by mablae** [comment]
Hello Jörg, 

I need to downgrade to ES 1.4.5 cause Elastica Client lib does not support 1.5 yet ... 

And the bundle plugin is not working in version 1.4.4.0

Even if not used in any mapping, my index creation fails. Elasticsearch logs are empty, no clue what goes wrong. 

After removing bundle plugin everything is fine again

If I can help with debugging it, just let me know... I would like to use the plugin, but it breaks :disappointed:

**Comment by jprante** [comment]
Bundle plugin 1.4.4.0 tests pass under ES 1.4.5 so I do not think there is a problem at all.

If you have no error messages or reproduction steps, it is not possible to analyze situation.

I recommend official PHP client at https://github.com/elastic/elasticsearch-php

**Comment by mablae** [comment]
This behaivor is reproducible: When I i install the bundle plugin, the indexing fails, removing it again, and everything is fine. 

I will try out the official client, thanks for the pointer. But I never had issues with ruflin/Elastica which is very popular, too. Also the client doesn't know about that plugin (not using any mappings yet)

Thanks for your help again. ;-)
